/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package openedi.exe;

import openedi.converter.Library;

public class App {
    public String getGreeting() {
        return "Hello world." + Library.someLibraryMethod();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
