/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package openedi.exe;

import openedi.converter.Reader;

import java.io.FileInputStream;

public class App {
    public static void main(String[] args) throws Exception {
        try {
            Reader reader = new Reader();
            FileInputStream stream = new FileInputStream("../samples/noname_order_sample_from_REXEL");
            reader.run(stream);
        } catch (Exception e) {
            System.out.println("Exception " + e.toString());
        }
    }
}
