/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package openedi.converter;

public class Library {
    static public boolean someLibraryMethod() {
        return true;
    }
}
