name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'
      - run: |
          cd java
          make jar

      - name: Upload server jar
        uses: actions/upload-artifact@v4
        with:
          name: server-jar
          retention-days: 7
          path: |
            java/server/target/universal/yopenedi-1.0-SNAPSHOT.zip
            java/email-fetcher/build/libs/email-fetcher-1.0-all.jar
            java/cli/build/libs/cli-1.0-all.jar
