name: Build
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'
      - run: |
          cd java
          make jar
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            java/server/target/universal/yopenedi-1.0-SNAPSHOT.zip
            java/email-fetcher/build/libs/email-fetcher-1.0-all.jar
            java/cli/build/libs/cli-1.0-all.jar
